#!/bin/bash

### Create pre-commit symlink if unset ###
GITDIR="";
if [ -d .git ]; then
  GITDIR=".git";
elif [ -f .git ]; then
  GITDIR=$(sed -n '/^gitdir:/{ s|.*: ||; p; }' .git);
fi
if [ ! -d "$GITDIR" ]; then
  echo "${0##*/}: error: unable to find git directory" 1>&2;
  exit 1;
fi
if [ ! -h "$GITDIR/hooks/pre-commit" ]; then
  if [ $(realpath --help 2>&1 | grep -c relative) != 0 ]; then
    HOOK=$(realpath --relative-to="$GITDIR/hooks" ./githook-pre-commit);
  else
    HOOK=$(readlink -f ./githook-pre-commit);
  fi
  ln -fs "$HOOK" "$GITDIR/hooks/pre-commit";
  echo "${0##*/}: creating git pre-commit hook symlink" 1>&2;
  exit 1;
fi


### Update versions on files ###
FILES=( $(git status --porcelain | sed 's| .* | |' | grep '^[MRA]') );
V=$(date -u +%Y.%m.%d);

check_change_after_staged () {
  [ "${2:1:1}" = "M" ] &&
    echo "${0##*/}: error: unable to update version due to change after staged: $1" 1>&2 &&
    exit 1;
}

VERSION_UPDATED=( - );
update_file_version () {
  echo "${0##*/}: updating version of $1" 1>&2;
  sed -r -i 's|([$"])Version:[^$"]*([$"])|\1Version: '"$V"'\2|' "$1";
  git add "$1";
  VERSION_UPDATED+=( "$1" );
}

already_updated () {
  echo $(printf "%s\n" "${VERSION_UPDATED[@]}" | grep -c "^$1\$");
}

n=1;
while [ "$n" -lt "${#FILES[@]}" ]; do
  [ $(already_updated "${FILES[$n]}") = 0 ] &&
    case "${FILES[$n]}" in
      *.cc )
        check_change_after_staged "${FILES[$n]}" "${FILES[$((n+1))]}";
        update_file_version "${FILES[$n]}";
        [ -e "${FILES[$n]/.cc/.h}" ] &&
          update_file_version "${FILES[$n]/.cc/.h}";
        ;;
      *.h )
        check_change_after_staged "${FILES[$n]}" "${FILES[$((n+1))]}";
        update_file_version "${FILES[$n]}";
        [ -e "${FILES[$n]/.h/.cc}" ] &&
          update_file_version "${FILES[$n]/.h/.cc}";
        ;;
    esac
  n=$((n+2));
done

if [ "${#VERSION_UPDATED[@]}" -gt 0 ]; then
  ### Update C++ documentation ###
  echo "### Update C++ documentation ###"
  cd lib;
  doxygen && moxygen -o ../doc/PageXML-API.md xml;
  [ "$?" != "0" ] && exit 1;
  cd ..;
  git add doc/PageXML-API.md;

  ### Test python wrapper and update documentation ###
  echo "### Test python wrapper and update documentation ###"
  cd py-pagexml;
  python setup.py test;
  [ "$?" != "0" ] && exit 1;
  python setup.py build_sphinx --quiet --builder text &&
    cp -p docs/_build/text/pagexml.txt API.rst;
  [ "$?" != "0" ] && exit 1;
  sed -i 's|pagexml\.pagexml|pagexml|g' API.rst;
  cd ..;
  git add py-pagexml/API.rst;
fi

exit 0;
