ARG UBUNTU_TAG=16.04
#ARG UBUNTU_TAG=18.04

FROM library/ubuntu:$UBUNTU_TAG

MAINTAINER Mauricio Villegas <mauricio@omnius.com>

ARG PYTHON_VERSION=3
#ARG PYTHON_VERSION=

ENV \
  DEBIAN_FRONTEND=noninteractive

RUN apt-get update --fix-missing \
 && apt-get install -y --no-install-recommends \
      less \
      nano \
      g++ \
      python$PYTHON_VERSION \
      python$PYTHON_VERSION-setuptools \
      python$PYTHON_VERSION-pkgconfig \
      python$PYTHON_VERSION-wheel \
      python$PYTHON_VERSION-dev \
      swig \
      libxml2-dev \
      libxslt1-dev \
      libopencv-dev \
      libgdal-dev \
      libboost-all-dev \
      ca-certificates \
      wget \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* \
 && cd /tmp \
 && wget https://github.com/tcnksm/ghr/releases/download/v0.12.0/ghr_v0.12.0_linux_amd64.tar.gz \
 && tar xzf ghr_v0.12.0_linux_amd64.tar.gz \
 && mv ghr_v0.12.0_linux_amd64/ghr /usr/local/bin/ \
 && if [ "$PYTHON_VERSION" = "3" ]; then ln -s /usr/bin/python3 /usr/local/bin/python; fi
