version: 2.1

dockerbuild: &dockerbuild
  steps:
    - checkout
    - run:
        name: "Build wheel package"
        command: |
          git submodule update --init
          cd py-pagexml
          ./setup.py bdist_wheel
          ./setup.py test
    - persist_to_workspace:
        root: .
        paths: ./py-pagexml/dist/*.whl

jobs:
  build-2004-py38:
    docker:
      - image: mauvilsa/pagexml:build-ubuntu20.04-py38
    <<: *dockerbuild
  build-2204-py310:
    docker:
      - image: mauvilsa/pagexml:build-ubuntu22.04-py310
    <<: *dockerbuild
  #publish-pypi:
  #  docker:
  #    - image: cimg/python:3.10
  #  steps:
  #    - attach_workspace:
  #        at: .
  #    - run:
  #        name: "Publish Release on PyPI"
  #        command: |
  #          pip3 install -U twine
  #          twine upload --repository-url "${PYPI_URL}" --username "${PYPI_USER}" --password "${PYPI_PASS}" ./py-pagexml/dist/*.whl
  publish-github:
    docker:
      - image: cibuilds/github:0.12.0
    steps:
      - attach_workspace:
          at: .
      - run:
          name: "Publish Release on GitHub"
          command: |
            ghr -t ${GITHUB_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_SHA1} ${CIRCLE_TAG} ./py-pagexml/dist/

tagfilter: &tagfilter
  filters:
    branches:
      ignore: /.*/
    tags:
      only: /^\d+\.\d+\.\d+$/

workflows:
  version: 2
  main:
    jobs:
      - build-2004-py38:
          <<: *tagfilter
      - build-2204-py310:
          <<: *tagfilter
      #- publish-pypi:
      #    <<: *tagfilter
      #    context: pagexml-context
      #    requires:
      #      - build-1804-py36
      #      - build-2004-py38
      - publish-github:
          <<: *tagfilter
          context: pagexml-context
          requires:
            - build-2004-py38
            - build-2204-py310
