ARG UBUNTU_TAG=18.04

FROM library/ubuntu:$UBUNTU_TAG

MAINTAINER Mauricio Villegas <mauricio@omnius.com>

ENV \
  DEBIAN_FRONTEND=noninteractive

RUN apt-get update --fix-missing \
 && apt-get install -y --no-install-recommends \
      less \
      nano \
      build-essential \
      python3 \
      python3-setuptools \
      python3-pkgconfig \
      python3-wheel \
      python3-dev \
      swig \
      libxml2-dev \
      libxslt1-dev \
      libopencv-dev \
      libgdal-dev \
      libboost-all-dev \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/* \
 && ln -s /usr/bin/python3 /usr/local/bin/python

COPY lib /opt/pagexml/lib
COPY py-pagexml /opt/pagexml/py-pagexml

WORKDIR /opt/pagexml/py-pagexml

RUN ./setup.py bdist_wheel \
 && ./setup.py install \
 && ./setup.py test
