FROM library/ubuntu:16.04

MAINTAINER Mauricio Villegas <mauricio@searchink.com>

### Install pre-requisites ###
RUN apt-get update --fix-missing \
 && DEBIAN_FRONTEND=noninteractive apt-get install -y --no-install-recommends \
      less \
      nano \
      python3 \
      python3-pip \
      libxml2:amd64 \
      libxslt1.1:amd64 \
      libopencv-highgui2.4v5:amd64 \
      libopencv-imgproc2.4v5:amd64 \
      libopencv-core2.4v5:amd64 \
 && apt-get clean \
 && rm -rf /var/lib/apt/lists/*

### Install the software ###
COPY dist /tmp
RUN pip3 install /tmp/pagexml-*-linux_x86_64.whl \
 && rm /tmp/*
